### ISSUE TITLE
Problems with Kali linux

### ISSUE THREAD

**Issue by jonathanmarp** [jonathanmarp/ccm#6]
**Problems I find if using linux times**

The problem shown is as I recall about memory after compile
So when I use ls, pwd, cd, exit it's okay. But if using
Aside from the syntax there will be errors. So if 
Someone can help to solve the problem. Thank

**Comment by jonathanmarp** [comment]
**For termux there is a time error in the compile with problems in the section**
```C++
std::vector<std::string> pwrt;
```
In ccm.cpp line 78

**Comment by jonathanmarp** [comment]
error: implicit instantiation of undefined template 'std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>>'

**Comment by thekotekjournal** [comment]
For Kali linux i can. But for termux iam so sorry i can't.

**Comment by thekotekjournal** [comment]
issue moved to https://github.com/jonathanmarp/ccm/issues/7
