### ISSUE TITLE
issue moved to https://github.com/jonathanmarp/ccm/issues/7

### ISSUE THREAD

**Issue by thekotekjournal** [jonathanmarp/ccm#8]
issue moved to https://github.com/jonathanmarp/ccm/issues/7

_Originally posted by @thekotekjournal in https://github.com/jonathanmarp/ccm/issues/6#issuecomment-780595962_

**Comment by thekotekjournal** [comment]
# Error About Vector C++ in termux clang

If you can help please help. Thank you

```bash
error: implicit instantiation of undefined template 'std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>>'
```

**Comment by jonathanmarp** [comment]
Thank you for all my help in answering the lack of libraries that are not included is #include<vector>

**Comment by jonathanmarp** [comment]
Vector
